name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Download Rattletrap
      run: |
        wget -q https://github.com/tfausak/rattletrap/releases/download/<version>/rattletrap-linux
        chmod +x rattletrap-linux
        mv rattletrap-linux ./rattletrap
    - name: Run tests
      run: cargo test --verbose